[[plugins]]
repo = 'rodjek/vim-puppet'
on_i = 1

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'
#
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#if = 'has("nvim")'
#if = 'has("python3")'
#on_i = 1
#hook_source = '''
#let g:deoplete#enable_at_startup = 1
#let g:deoplete#enable_ignore_case = 1
#let g:deoplete#enable_smart_case = 1
#let g:deoplete#auto_complete_delay = 0
#inoremap <expr><tab> pumvisible() ? "\<C-n>" :
#        \ neosnippet#expandable_or_jumpable() ?
#        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
#'''
#
#
